import Link from "next/link";
import Image from "next/image";
import { ArrowLeft, BarChart3, ChevronLeft, FileCheck2, ShieldCheck, Sparkles, TrendingUp } from "lucide-react";
import { projects } from "@/lib/data";

const fmt = (n:number) => new Intl.NumberFormat("fa-IR").format(n);

export default function Home() {
  return <main>
    <nav className="nav"><Link href="/" className="brand"><span className="brand-mark">M</span><span>مِتریکا</span></Link><div className="nav-links"><Link href="/projects">پروژه‌ها</Link><Link href="/marketplace">بازار ثانویه</Link><Link href="/how-it-works">چطور کار می‌کند؟</Link><Link href="/about">درباره ما</Link><Link href="/blog">مجله</Link></div><div className="nav-actions"><Link href="/dashboard" className="ghost-btn">ورود</Link><Link href="/projects" className="primary-btn">شروع سرمایه‌گذاری <ArrowLeft size={16}/></Link></div></nav>
    <section className="hero container"><div className="hero-copy"><div className="eyebrow"><Sparkles size={15}/> نسخه نمایشی </div><h1>متر به متر<br/><em>خانه </em><br/>بسازید</h1><p>مِتریکا دسترسی شفاف و مرحله‌ای به پروژه‌های منتخب ساختمانی را برای شما ساده می‌کند؛ با گزارش پیشرفت، اسناد نمونه و داشبوردی که همیشه به‌روز است.</p><div className="hero-actions"><Link href="/projects" className="primary-btn large">مشاهده پروژه‌ها <ArrowLeft size={18}/></Link><Link href="/how-it-works" className="text-btn">نحوه کار مِتریکا <ChevronLeft size={18}/></Link></div><p className="micro">سرمایه‌گذاری در ملک دارای ریسک است و بازدهی تضمین‌شده نیست.</p></div><div className="hero-visual"><div className="grid-lines"/><div className="architect"><div className="block b1"/><div className="block b2"/><div className="block b3"/><div className="block b4"/><div className="block b5"/><div className="block b6"/></div><div className="live-card"><span>شروع سرمایه‌گذاری از</span><strong>۵۰۰ هزار تومان</strong><small>دمو • بدون تراکنش واقعی</small></div></div></section>
    <section className="trust container"><div><FileCheck2/><span>مدارک و خلاصه قرارداد</span><small>نمونه نمایشی</small></div><div><TrendingUp/><span>گزارش پیشرفت ساخت</span><small>به‌روزرسانی دوره‌ای</small></div><div><BarChart3/><span>تنوع پروژه و شهر</span><small>برای مدیریت ریسک</small></div><div><ShieldCheck/><span>طراحی شفاف</span><small>بدون ادعای مجوز</small></div></section>
    <section className="section container"><div className="section-head"><div><span className="eyebrow">انتخاب سردبیر</span><h2>پروژه‌های منتخب</h2></div><Link href="/projects" className="text-btn">مشاهده همه <ArrowLeft size={16}/></Link></div><div className="project-grid">{projects.slice(0,4).map((p,i)=><Link href={`/projects/${p.slug}`} className={`project-card ${i===0?"featured":""}`} key={p.slug}><div className="project-art"><Image src={p.image} alt={`رندر نمایشی ${p.name}`} fill sizes="(max-width: 800px) 100vw, 50vw" style={{objectFit:"cover"}}/><span>{p.stage}</span><div className="art-label">{p.code}</div></div><div className="project-body"><div className="project-top"><div><h3>{p.name}</h3><p>{p.city} • {p.type}</p></div><span className={`risk ${p.risk}`}>{p.riskLabel}</span></div><div className="metric-row"><div><small>قیمت هر واحد</small><b>{fmt(p.unitPrice)} <i>تومان</i></b></div><div><small>پیشرفت تأمین</small><b>{p.funding}%</b></div></div><div className="progress"><span style={{width:`${p.funding}%`}}/></div></div></Link>)}</div></section>
    <section className="section dark-section"><div className="container"><div className="section-head"><div><span className="eyebrow">مسیر شما</span><h2>سه گام تا اولین متر</h2></div></div><div className="steps"><div><span>۰۱</span><h3>ثبت‌نام و تکمیل اطلاعات</h3><p>ساخت پروفایل سرمایه‌گذار در چند دقیقه. احراز هویت در این نسخه شبیه‌سازی شده است.</p></div><div><span>۰۲</span><h3>انتخاب پروژه</h3><p>پروژه‌ها را بر اساس شهر، مرحله ساخت و سطح ریسک مقایسه کنید.</p></div><div><span>۰۳</span><h3>خرید و پیگیری</h3><p>واحدهای نمایشی بخرید و گزارش پیشرفت و ارزش illustrative را ببینید.</p></div></div></div></section>
    <section className="section container risk-section"><div className="risk-panel"><div><span className="eyebrow">شفافیت مقدم است</span><h2>سرمایه‌گذاری بدون وعده</h2><p>این محصول یک MVP آموزشی است. هیچ عددی پیش‌بینی یا تضمین بازدهی نیست و خرید، فروش، پرداخت و مالکیت در آن واقعی نیست.</p></div><Link href="/risk-disclosure" className="secondary-btn">مطالعه افشای ریسک <ArrowLeft size={16}/></Link></div></section>
    <footer className="footer"><div className="container footer-inner"><div><Link href="/" className="brand"><span className="brand-mark">M</span><span>مِتریکا</span></Link><p>سرمایه‌گذاری در ملک، به اندازه توان شما.</p></div><div className="footer-links"><Link href="/faq">سؤالات متداول</Link><Link href="/risk-disclosure">افشای ریسک</Link><Link href="/about">درباره ما</Link><span>© ۱۴۰۵ مِتریکا • نسخه نمایشی</span></div></div></footer>
  </main>
}
