export type Project={slug:string;name:string;code:string;city:string;type:string;stage:string;funding:number;unitPrice:number;min:number;risk:string;riskLabel:string;completion:string;area:number;description:string;image:string};
export const projects:Project[]=[
{slug:"baran-tower",name:"برج باران",code:"MT-01",city:"تهران، منطقه ۲",type:"مسکونی",stage:"اسکلت فلزی",funding:68,unitPrice:18500000,min:500000,risk:"medium",riskLabel:"متوسط",completion:"پاییز ۱۴۰۶",area:4200,description:"پروژه‌ای ۲۴ طبقه با تمرکز بر نور طبیعی و فضاهای اشتراکی.",image:"/projects/baran-tower.png"},
{slug:"rudsar-garden",name:"باغ رودسر",code:"MT-02",city:"رشت، گلسار",type:"ویلایی",stage:"فونداسیون",funding:42,unitPrice:9800000,min:1000000,risk:"high",riskLabel:"بالا",completion:"بهار ۱۴۰۷",area:6100,description:"مجموعه ویلاهای کم‌تراکم در حاشیه شهر با فضای سبز یکپارچه.",image:"/projects/rudsar-garden.png"},
{slug:"shiraz-courtyard",name:"حیات شیراز",code:"MT-03",city:"شیراز، معالی‌آباد",type:"تجاری",stage:"نازک‌کاری",funding:81,unitPrice:22400000,min:500000,risk:"low",riskLabel:"پایین",completion:"تابستان ۱۴۰۶",area:2800,description:"بازآفرینی یک گذر تجاری قدیمی با رویکرد پیاده‌محور.",image:"/projects/shiraz-courtyard.png"},
{slug:"karaj-line",name:"بلولاین کرج",code:"MT-04",city:"کرج، جهانشهر",type:"مسکونی",stage:"پروانه ساخت",funding:27,unitPrice:7600000,min:500000,risk:"high",riskLabel:"بالا",completion:"زمستان ۱۴۰۷",area:8900,description:"مجتمع مسکونی ماژولار با پلان‌های منعطف برای خانواده‌های جوان.",image:"/projects/karaj-line.png"},
{slug:"mashhad-axis",name:"عمارت مشهد",code:"MT-05",city:"مشهد، سجاد",type:"اداری",stage:"اسکلت بتنی",funding:54,unitPrice:13200000,min:1000000,risk:"medium",riskLabel:"متوسط",completion:"پاییز ۱۴۰۶",area:3600,description:"ساختمان اداری با هسته خدماتی و سالن‌های جلسات اشتراکی.",image:"/projects/mashhad-axis.png"},
{slug:"tehran-north",name:"ستاره شمال",code:"MT-06",city:"تهران، منطقه ۱",type:"مسکونی",stage:"تحویل نزدیک",funding:93,unitPrice:31500000,min:500000,risk:"low",riskLabel:"پایین",completion:"بهار ۱۴۰۶",area:1900,description:"پروژه بوتیک با تعداد واحد محدود و چشم‌انداز شهری.",image:"/projects/tehran-north.png"},
{slug:"rasht-harir",name:"حریر رشت",code:"MT-07",city:"رشت، منظریه",type:"تجاری",stage:"فونداسیون",funding:35,unitPrice:8700000,min:500000,risk:"high",riskLabel:"بالا",completion:"تابستان ۱۴۰۷",area:4700,description:"مرکز محلی خرید و تجربه با حیاط مرکزی باران‌گیر.",image:"/projects/rasht-harir.png"},
{slug:"shiraz-narenj",name:"نارنجستان",code:"MT-08",city:"شیراز، فرهنگ‌شهر",type:"ویلایی",stage:"اسکلت فلزی",funding:61,unitPrice:14700000,min:1000000,risk:"medium",riskLabel:"متوسط",completion:"پاییز ۱۴۰۶",area:5300,description:"خانه‌های حیاط‌دار با معماری معاصر و مصالح بومی.",image:"/projects/shiraz-narenj.png"}
];
